"""ftre-agent：Agent 稳定契约包。

只包含 AgentService、输入/结果模型、身份 Registry、Agent Hook 契约和跨包
配置快照；不包含 AgentLoop、LLM Client 或任何工具执行实现。`ftre_agent.plugin`
通过 Provider Plugin 唯一发布 ``agents`` Service；Runtime 由
``ftre-agent-runtime`` Package 提供，并注册到该 Service。

依赖边界：本包不依赖 ftre Host（``ftre.services.*``），可被测试替身和其他
Host 独立引用。
"""

from .config import AgentConfig, LLMConfig, build_llm_config, sanitize_agent_effort
from .contracts import (
    AgentCreateSpec,
    AgentHandle,
    AgentListener,
    AgentResumeSpec,
    AgentRunRequest,
    AgentRunResult,
    AgentRuntimeFactory,
    AgentRuntimeHandle,
    AgentStreamEnvelope,
    AgentView,
    RunOptions,
    RunReservation,
    RunStatus,
    RuntimeControlPort,
)
from .errors import (
    AgentAlreadyExistsError,
    AgentBusyError,
    AgentNotFoundError,
    AgentServiceError,
    FactoryAlreadyRegisteredError,
    FactoryNotRegisteredError,
    FactoryRegistrationMismatchError,
    InvalidFactoryError,
    InvalidRunRequestError,
    RunConflictError,
    ServiceClosedError,
)
from .event import (
    AgentStreamEvent,
    EventBase,
    ReplyEndEvent,
    ReplyStartEvent,
    UserMessageEvent,
)
from .hooks import (
    AGENT_AFTER_RUN,
    AGENT_AFTER_RUN_SPEC,
    AGENT_BEFORE_REASONING,
    AGENT_BEFORE_REASONING_SPEC,
    AGENT_BEFORE_RUN,
    AGENT_BEFORE_RUN_SPEC,
    AGENT_RUN_ERROR,
    AGENT_RUN_ERROR_SPEC,
    AGENT_STOP_DECISION,
    AGENT_STOP_DECISION_SPEC,
    LLM_ERROR,
    LLM_ERROR_SPEC,
    LLM_STREAM,
    LLM_STREAM_SPEC,
    AfterRunPayload,
    AgentSubject,
    AllowRun,
    BeforeReasoningPayload,
    BeforeReasoningResult,
    BeforeRunPayload,
    ContinueTurn,
    DeferRun,
    LLMErrorDecision,
    LLMErrorPayload,
    LLMStreamPayload,
    RejectRun,
    RequestErrorPayload,
    RetryRequest,
    StopDecisionPayload,
    StopTurn,
)
from .message import (
    AssistantMsg,
    ContentBlock,
    Msg,
    SystemMsg,
    TextBlock,
    ThinkingBlock,
    ToolCallBlock,
    ToolResultBlock,
    UserMsg,
    from_openai_message,
    to_openai_message,
)
from .registry import AgentRecord, AgentRegistry, HookScopeCarrier
from .service import AgentService, FactoryRegistration
from .status import AgentStatus
from .tool import (
    Injected,
    PermissionBehavior,
    PermissionContext,
    PermissionDecision,
    PermissionRequest,
    PermissionRule,
    ToolCallRequest,
    ToolContext,
    ToolDefinition,
    ToolExecutionResult,
    ToolParameter,
    ToolSchema,
    ToolView,
    tool,
)
from .tracing import RunStatus as TraceRunStatus
from .tracing import RunType, Tracer, TraceRun, TraceSpan
from .types import ReplyFinishedReason

__all__ = [
    "AGENT_AFTER_RUN",
    "AGENT_AFTER_RUN_SPEC",
    "AGENT_BEFORE_REASONING",
    "AGENT_BEFORE_REASONING_SPEC",
    "AGENT_BEFORE_RUN",
    "AGENT_BEFORE_RUN_SPEC",
    "AGENT_RUN_ERROR",
    "AGENT_RUN_ERROR_SPEC",
    "AGENT_STOP_DECISION",
    "AGENT_STOP_DECISION_SPEC",
    "LLM_ERROR",
    "LLM_ERROR_SPEC",
    "LLM_STREAM",
    "LLM_STREAM_SPEC",
    "AfterRunPayload",
    "AgentAlreadyExistsError",
    "AgentBusyError",
    "AgentConfig",
    "AgentCreateSpec",
    "AgentHandle",
    "AgentListener",
    "AgentNotFoundError",
    "AgentRecord",
    "AgentRegistry",
    "AgentResumeSpec",
    "AgentRunRequest",
    "AgentRunResult",
    "AgentRuntimeFactory",
    "AgentRuntimeHandle",
    "AgentService",
    "AgentServiceError",
    "AgentStatus",
    "AgentStreamEnvelope",
    "AgentStreamEvent",
    "AgentSubject",
    "AgentView",
    "AllowRun",
    "AssistantMsg",
    "BeforeReasoningPayload",
    "BeforeReasoningResult",
    "BeforeRunPayload",
    "ContentBlock",
    "ContinueTurn",
    "DeferRun",
    "EventBase",
    "FactoryAlreadyRegisteredError",
    "FactoryNotRegisteredError",
    "FactoryRegistration",
    "FactoryRegistrationMismatchError",
    "HookScopeCarrier",
    "Injected",
    "InvalidFactoryError",
    "InvalidRunRequestError",
    "LLMConfig",
    "LLMErrorDecision",
    "LLMErrorPayload",
    "LLMStreamPayload",
    "Msg",
    "PermissionBehavior",
    "PermissionContext",
    "PermissionDecision",
    "PermissionRequest",
    "PermissionRule",
    "RejectRun",
    "ReplyEndEvent",
    "ReplyFinishedReason",
    "ReplyStartEvent",
    "RequestErrorPayload",
    "RetryRequest",
    "RunConflictError",
    "RunOptions",
    "RunReservation",
    "RunStatus",
    "RunType",
    "RuntimeControlPort",
    "ServiceClosedError",
    "StopDecisionPayload",
    "StopTurn",
    "SystemMsg",
    "TextBlock",
    "ThinkingBlock",
    "ToolCallBlock",
    "ToolCallRequest",
    "ToolContext",
    "ToolDefinition",
    "ToolExecutionResult",
    "ToolParameter",
    "ToolResultBlock",
    "ToolSchema",
    "ToolView",
    "TraceRun",
    "TraceRunStatus",
    "TraceSpan",
    "Tracer",
    "UserMessageEvent",
    "UserMsg",
    "build_llm_config",
    "from_openai_message",
    "sanitize_agent_effort",
    "to_openai_message",
    "tool",
]
