"""ftre 的持久消息 Inbox Plugin。

根模块只导出轻量模型，避免 ``import ftre_inbox`` 在独立 wheel 中反向加载 ftre
Gateway。运行时 Service/Plugin 通过显式子模块导入，宿主仍可使用同一个稳定包名。
"""

from .models import InboxSnapshot, QueueItem, QueueTarget
from .protocol import InboundMessage

__all__ = [
    "INBOX_ADMITTED",
    "INBOX_ADMITTED_SPEC",
    "INBOX_BEFORE_ADMIT",
    "INBOX_BEFORE_ADMIT_SPEC",
    "INBOX_BEFORE_CLAIM",
    "INBOX_BEFORE_CLAIM_SPEC",
    "INBOX_CHANGED",
    "INBOX_CHANGED_SPEC",
    "INBOX_CLAIMED",
    "INBOX_CLAIMED_SPEC",
    "INBOX_DEFERRED",
    "INBOX_DEFERRED_SPEC",
    "INBOX_DELIVERED",
    "INBOX_DELIVERED_SPEC",
    "INBOX_DISCARDED",
    "INBOX_DISCARDED_SPEC",
    "INBOX_ERROR",
    "INBOX_ERROR_SPEC",
    "INBOX_FAILED",
    "INBOX_FAILED_SPEC",
    "INBOX_STATUS_CHANGED",
    "INBOX_STATUS_CHANGED_SPEC",
    "AllowAdmission",
    "BeforeAdmissionPayload",
    "BeforeClaimPayload",
    "EnterClaim",
    "InboundMessage",
    "InboxAdmissionPayload",
    "InboxChangedPayload",
    "InboxClaimedPayload",
    "InboxDeferredPayload",
    "InboxDeliveredPayload",
    "InboxDiscardedPayload",
    "InboxErrorPayload",
    "InboxFailedPayload",
    "InboxService",
    "InboxSnapshot",
    "InboxStatusPayload",
    "QueueItem",
    "QueueTarget",
    "RejectAdmission",
    "RejectClaim",
]


def __getattr__(name: str):
    """按需加载 Service/Hook，保持独立包的基础 import 无宿主副作用。"""
    if name == "InboxService":
        from .service import InboxService

        return InboxService
    if name in {
        "BeforeAdmissionPayload",
        "AllowAdmission",
        "RejectAdmission",
        "BeforeClaimPayload",
        "InboxAdmissionPayload",
        "InboxClaimedPayload",
        "InboxDeferredPayload",
        "InboxDeliveredPayload",
        "InboxErrorPayload",
        "InboxFailedPayload",
        "InboxDiscardedPayload",
        "EnterClaim",
        "INBOX_BEFORE_CLAIM",
        "INBOX_BEFORE_CLAIM_SPEC",
        "INBOX_ADMITTED",
        "INBOX_ADMITTED_SPEC",
        "INBOX_BEFORE_ADMIT",
        "INBOX_BEFORE_ADMIT_SPEC",
        "INBOX_CLAIMED",
        "INBOX_CLAIMED_SPEC",
        "INBOX_CHANGED",
        "INBOX_CHANGED_SPEC",
        "INBOX_DEFERRED",
        "INBOX_DEFERRED_SPEC",
        "INBOX_DELIVERED",
        "INBOX_DELIVERED_SPEC",
        "INBOX_ERROR",
        "INBOX_ERROR_SPEC",
        "INBOX_FAILED",
        "INBOX_FAILED_SPEC",
        "INBOX_DISCARDED",
        "INBOX_DISCARDED_SPEC",
        "INBOX_STATUS_CHANGED",
        "INBOX_STATUS_CHANGED_SPEC",
        "InboxChangedPayload",
        "InboxStatusPayload",
        "RejectClaim",
    }:
        from .hooks import (
            INBOX_ADMITTED,
            INBOX_ADMITTED_SPEC,
            INBOX_BEFORE_ADMIT,
            INBOX_BEFORE_ADMIT_SPEC,
            INBOX_BEFORE_CLAIM,
            INBOX_BEFORE_CLAIM_SPEC,
            INBOX_CHANGED,
            INBOX_CHANGED_SPEC,
            INBOX_CLAIMED,
            INBOX_CLAIMED_SPEC,
            INBOX_DEFERRED,
            INBOX_DEFERRED_SPEC,
            INBOX_DELIVERED,
            INBOX_DELIVERED_SPEC,
            INBOX_DISCARDED,
            INBOX_DISCARDED_SPEC,
            INBOX_ERROR,
            INBOX_ERROR_SPEC,
            INBOX_FAILED,
            INBOX_FAILED_SPEC,
            INBOX_STATUS_CHANGED,
            INBOX_STATUS_CHANGED_SPEC,
            AllowAdmission,
            BeforeAdmissionPayload,
            BeforeClaimPayload,
            EnterClaim,
            InboxAdmissionPayload,
            InboxChangedPayload,
            InboxClaimedPayload,
            InboxDeferredPayload,
            InboxDeliveredPayload,
            InboxDiscardedPayload,
            InboxErrorPayload,
            InboxFailedPayload,
            InboxStatusPayload,
            RejectAdmission,
            RejectClaim,
        )

        return {
            "AllowAdmission": AllowAdmission,
            "BeforeAdmissionPayload": BeforeAdmissionPayload,
            "RejectAdmission": RejectAdmission,
            "BeforeClaimPayload": BeforeClaimPayload,
            "InboxAdmissionPayload": InboxAdmissionPayload,
            "InboxClaimedPayload": InboxClaimedPayload,
            "InboxDeferredPayload": InboxDeferredPayload,
            "InboxDeliveredPayload": InboxDeliveredPayload,
            "InboxErrorPayload": InboxErrorPayload,
            "InboxFailedPayload": InboxFailedPayload,
            "InboxDiscardedPayload": InboxDiscardedPayload,
            "EnterClaim": EnterClaim,
            "INBOX_BEFORE_CLAIM": INBOX_BEFORE_CLAIM,
            "INBOX_BEFORE_CLAIM_SPEC": INBOX_BEFORE_CLAIM_SPEC,
            "INBOX_ADMITTED": INBOX_ADMITTED,
            "INBOX_ADMITTED_SPEC": INBOX_ADMITTED_SPEC,
            "INBOX_BEFORE_ADMIT": INBOX_BEFORE_ADMIT,
            "INBOX_BEFORE_ADMIT_SPEC": INBOX_BEFORE_ADMIT_SPEC,
            "INBOX_CLAIMED": INBOX_CLAIMED,
            "INBOX_CLAIMED_SPEC": INBOX_CLAIMED_SPEC,
            "INBOX_CHANGED": INBOX_CHANGED,
            "INBOX_CHANGED_SPEC": INBOX_CHANGED_SPEC,
            "INBOX_DEFERRED": INBOX_DEFERRED,
            "INBOX_DEFERRED_SPEC": INBOX_DEFERRED_SPEC,
            "INBOX_DELIVERED": INBOX_DELIVERED,
            "INBOX_DELIVERED_SPEC": INBOX_DELIVERED_SPEC,
            "INBOX_ERROR": INBOX_ERROR,
            "INBOX_ERROR_SPEC": INBOX_ERROR_SPEC,
            "INBOX_FAILED": INBOX_FAILED,
            "INBOX_FAILED_SPEC": INBOX_FAILED_SPEC,
            "INBOX_DISCARDED": INBOX_DISCARDED,
            "INBOX_DISCARDED_SPEC": INBOX_DISCARDED_SPEC,
            "INBOX_STATUS_CHANGED": INBOX_STATUS_CHANGED,
            "INBOX_STATUS_CHANGED_SPEC": INBOX_STATUS_CHANGED_SPEC,
            "InboxChangedPayload": InboxChangedPayload,
            "InboxStatusPayload": InboxStatusPayload,
            "RejectClaim": RejectClaim,
        }[name]
    raise AttributeError(name)
